### ISSUE TITLE
Not working on windows...

### ISSUE THREAD

**Issue by brentonhouse** [FokkeZB/TiCons-CLI#25]
I am getting an error when trying to run on Windows 7.  I will try to debug it to get more info...

```
C:\test>ticons splashes -t -d .\output "xhdpi (640x960).png"
[INFO]  Reading input dimensions

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by brentonhouse** [comment]
Seems to be an issue w/ gm not ticons-cli.  

You can close this issue.  Thanks!
