### ISSUE TITLE
TypeError: Invalid Version: true

### ISSUE THREAD

**Issue by zineer** [FokkeZB/TiCons-CLI#37]
I'm trying to use ticons (0.14.0) for generating icons outside of a Titanium app. I can successfully create Splash images, but get an error when I try to create Icons:

```
$ ticons icons splash-generic.png --output-dir part --alloy --platforms iphone,ipad,android --sdk-version '4.0.0' -t
[INFO]  Reading input dimensions
[DEBUG] Initialized config:

 type: icon
 cli: true
 input: /Users/foo/CordovaApps/splash-generic.png
 platforms: iphone, ipad, android
 radius: 0
 sdkVersion: true
 locale:
 minDpi: 160
 maxDpi: 480
 orientation:
 fix: true
 nine: true
 crop: true
 label: false
 outputDir: part
 assetsDir: app/assets
 alloy: true
 trace: true
 inputWidth: 2208
 inputHeight: 2208
 inputRatio: 1
 widget: false
 ios: true
 iphone: true
 ipad: true
 android: true
 mobileweb: false
 blackberry: false
 tizen: false
 apple-watch: false
 windows: false


/usr/local/lib/node_modules/ticons/node_modules/semver/semver.js:279
    throw new TypeError('Invalid Version: ' + version);
          ^
TypeError: Invalid Version: true
    at new SemVer (/usr/local/lib/node_modules/ticons/node_modules/semver/semver.js:279:11)
    at compare (/usr/local/lib/node_modules/ticons/node_modules/semver/semver.js:569:10)
    at lt (/usr/local/lib/node_modules/ticons/node_modules/semver/semver.js:603:10)
    at cmp (/usr/local/lib/node_modules/ticons/node_modules/semver/semver.js:644:21)
    at Comparator.test (/usr/local/lib/node_modules/ticons/node_modules/semver/semver.js:711:10)
    at testSet (/usr/local/lib/node_modules/ticons/node_modules/semver/semver.js:1058:17)
    at Range.test (/usr/local/lib/node_modules/ticons/node_modules/semver/semver.js:1050:9)
    at Function.satisfies (/usr/local/lib/node_modules/ticons/node_modules/semver/semver.js:1096:16)
    at /usr/local/lib/node_modules/ticons/lib/jobs.js:389:53
    at Function._.each._.forEach (/usr/local/lib/node_modules/ticons/node_modules/underscore/underscore.js:158:9)
```

I get the same result whether I specify SDK version in quotes or not. Any thoughts? Thanks!

**Comment by FokkeZB** [comment]
Thanks! Just published new version with fix.
